^POST /pet$: addPet
^PUT /pet$: updatePet
^GET /pet/findByStatus$: findPetsByStatus
^GET /pet/.*: getPetById
^POST /pet/.*: updatePetWithForm
^DELETE /pet/.*: deletePet
^POST /pet/.*/uploadImage$: uploadFile
^GET /store/inventory: getInventory
^POST /store/order: placeOrder
^GET /store/order/.*: getOrderById
^DELETE /store/order/.*: deleteOrder
^POST /user$: createUser
^POST /user/createWithArray$: createUsersWithArrayInput
^POST /user/createWithList$: createUsersWithListInput
^GET /user/login$: loginUser
^GET /user/logout: logoutUser
^GET /user/.*: getUserByName
^PUT /user/.*: updateUser
^DELETE /user/.*: deleteUser